// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package llrb

// Compare node to newNode
func (node *NodeInt) Compare(v int) int {
	if node.Value < v {
		return -1
	}
	if node.Value > v {
		return 1
	}
	return 0
}

// Compare node to newNode
func (node *NodeFloat64) Compare(v float64) int {
	if node.Value < v {
		return -1
	}
	if node.Value > v {
		return 1
	}
	return 0
}

// Compare node to newNode
func (node *NodeString) Compare(v string) int {
	if node.Value < v {
		return -1
	}
	if node.Value > v {
		return 1
	}
	return 0
}

// Compare node to newNode
func (node *NodeByte) Compare(v byte) int {
	if node.Value < v {
		return -1
	}
	if node.Value > v {
		return 1
	}
	return 0
}
